# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
production:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: tres_home_assignment_backend
  pool: 5
  host: localhost
  username: <%= ENV['DATABASE_PRODUCTION_USERNAME'] %>
  password: <%= ENV['DATABASE_PRODUCTION_PASSWORD'] %>

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: tres_home_assignment_backend
  pool: 5
  host: localhost
  username: amitshefer
  password: Aa123456
